
function y = mean(x)

% ESTA FUNÇÃO CALCULA (dá como output) O VALOR MÉDIO DAS ENTRADAS DE UMA
% MATRIZ x DE DIMENSÃO mxn.

% NOTE QUE, PARA MATRIZES, O VALOR MÉDIO mean(x) DA MATRIZ x É UM VETOR
% LINHA CONSTITUIDO PELOS VALORES MÉDIOS DE CADA COLUNA DA MATRIZ

% ESTE m.FILE DEVE SER GRAVADO COM O NOME DADO À function, NESTE CASO
% mean, SEGUIDO DE UM PARÊNTESIS ONDE CONSTA O ÚNICO INPUT, A MATRIZ x.

% A MATRIZ x NÃO É AQUI EXPLICITADA, VISTO QUE A VANTAGEM DESTE m.FILE 
% É SERVIR DE SUPORTE NA EXECUÇÃO DE OUTROS m.FILES; SÃO ESTES ÚLTIMOS 
% QUE VÃO "PEDIR" INDICAÇÃO DE x (OU JÁ TÊM A MATRIZ x DEFINIDA COM ESTA 
% DESIGNAÇÃO).


[m,n] = size(x);  % COMANDO size PARA INDICAÇÃO DA DIMENSÃO mxn DA MATRIZ x

if m == 1

m = n;            % IDENTIFICAÇÃO PARA TRATAR CADA VETOR LINHA ISOLADAMENTE

end

y = sum(x)/m;  % FÓRMULA DO VALOR MÉDIO COM USO DO COMANDO sum

% NO FINAL DEVEMOS CORRER O m.FILE PARA VERIFICAR SE PEDE OS INPUTS
% PRETENDIDOS
